rails-cheap-advisor-crud/config/routes.rb
Rails.application.routes.draw do

  root 'restaurants#index'
  resources :restaurants

end

rails-cheap-advisor-crud/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rails-cheap-advisor-crud/app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates :name, presence: true
end

rails-cheap-advisor-crud/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

rails-cheap-advisor-crud/app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  before_action :set_restaurant, only: [:show, :update, :edit, :destroy]

  # GET /restaurants
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/:id
  def show
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # POST /restaurants/create

  def create
    # @restaurant = Restaurant.new(params[:restaurant])
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      #back to the form
    end
  end

  # GET /restaurants/:id/edit
  def edit
  end

  # PATCH/PUT /restaurants/:id
  def update
    @restaurant.update(restaurant_params)
    redirect_to restaurant_path(@restaurant)
  end

  # DELETE /restaurants/:id
  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end


  private
  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :stars)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

rails-cheap-advisor-crud/app/helpers/application_helper.rb
module ApplicationHelper
end

rails-cheap-advisor-crud/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CheapAdvisorCrud</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

rails-cheap-advisor-crud/app/views/restaurants/_form.html.erb
<%= form_for @restaurant do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.label :stars %>
  <%= f.number_field :stars %>

  <%= f.submit %>
<% end %>

rails-cheap-advisor-crud/app/views/restaurants/edit.html.erb
<h2>Update <%= @restaurant.name %></h2>

<%= render 'form' %>

rails-cheap-advisor-crud/app/views/restaurants/index.html.erb
<h2>Welcome to CheapAdvisor</h2>

<ul>
<% @restaurants.each do |restaurant| %>
  <li>

  <%= link_to restaurant.name, restaurant_path(restaurant) %>
  , <%= restaurant.address %> (<%= restaurant.stars %>)

  <%= link_to 'edit', edit_restaurant_path(restaurant) %>
  <%= link_to 'destroy', restaurant_path(restaurant), method: :delete, data: { confirm: 'Are you sure?' } %>

  </li>
<% end %>
</ul>

<p>
  <%= link_to 'New restaurant', new_restaurant_path %>
</p>

rails-cheap-advisor-crud/app/views/restaurants/new.html.erb
<h2>Add a restaurant</h2>

<%= render 'form' %>

rails-cheap-advisor-crud/app/views/restaurants/show.html.erb
<h2><%= @restaurant.name %></h2>
<p><%= @restaurant.address %></p>
<b>stars: <%= @restaurant.stars %></b>

<br>
<%= link_to 'Restaurants', root_path %>