rails-yelp-mvp/config/routes.rb
Rails.application.routes.draw do
  root 'restaurants#index'
  resources :restaurants do
    resources :reviews
    # post '/restaurants/:restaurant_id/reviews', to: 'reviews#create', as: :reviews
  end
end

rails-yelp-mvp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rails-yelp-mvp/app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews

  before_destroy :destroy_reviews

  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true
  validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"] }

  CATEGORIES = ["chinese", "italian", "japanese", "french", "belgian"]

  def average
    total = 0
    self.reviews.each do |review|
      total += review.rating
    end
    if total.zero?
      return { grade: 0,
               message: "There are no reviews yet for this restaurant" }
    else
      grade = total.to_f / reviews.length
      return { grade: grade,
               message: "#{grade} from reviews" }
    end
  end

  private

  def destroy_reviews
    self.reviews.each do |review|
      review.delete
    end
  end
end

rails-yelp-mvp/app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :restaurant, presence: true
  validates :content, presence: true
  validates :rating, presence: true
  validates :rating, numericality: { only_integer: true }
  validates :rating, inclusion: { in: [0, 1, 2, 3, 4, 5] }
end

rails-yelp-mvp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

rails-yelp-mvp/app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :delete]

  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def edit
    redirect_to restaurant_path(@restaurant)
  end

  def update
    redirect_to restaurant_path(@restaurant)
  end

  def delete
    redirect_to restaurant_path(@restaurant)
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

rails-yelp-mvp/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :delete]
  before_action :set_restaurant, only: [:new, :create]

  def index
    @reviews = Review.all
  end

  def show
  end

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    puts @review.valid?
    if @review.save
      puts "Saved"
      redirect_to restaurant_path(@restaurant)
    else
      puts "not saved"
      render :new
    end
  end

  def edit
    redirect_to restaurant_path(@restaurant)
  end

  def update
    redirect_to restaurant_path(@restaurant)
  end

  def delete
    redirect_to restaurant_path(@restaurant)
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end

  def set_review
    @review = Review.find(params[:id])
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end
end

rails-yelp-mvp/app/helpers/application_helper.rb
module ApplicationHelper
end

rails-yelp-mvp/app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

rails-yelp-mvp/app/helpers/reviews_helper.rb
module ReviewsHelper
end

rails-yelp-mvp/app/views/layouts/_navbar.html.erb
<div class='navbar text-center navbar-fixed'>
  <%= link_to "Presto", restaurants_path, { class: "navbar-header link-style-none" } %>

  <!-- <a href="#" onclick="scrollToRestaurants()">Browse restaurants<br>v</a> -->
</div>

rails-yelp-mvp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Presto</title>
    <%= csrf_meta_tags %>

    <link href="https://fonts.googleapis.com/css?family=Lora:700|Roboto" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class="container">
      <div class="row">
        <div class="col-md-8 col-md-offset-2">
          <%= yield %>
        </div>
      </div>
  </body>
</html>

rails-yelp-mvp/app/views/reviews/_new_review_form.html.erb
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.text_area :content, placeholder: 'Write a review', style: "width: 100%; min-height: 300px" %>
  <%= f.input :rating, as: :integer, style: "width: 50px", inline_label: 'Rating', error: 'Please rate the restaurant 1-5' %>
  <%= f.button :submit, class: "btn-main" %>
<% end %>

rails-yelp-mvp/app/views/reviews/new.html.erb
<%= link_to "< Back to restaurant page", restaurant_path(@restaurant), { class: "link-style-none btn-main" } %>

<h2>Create a new review for <%= @restaurant.name %>:</h2>

<%= render 'new_review_form' %>