rails-mister-cocktail/config/routes.rb
Rails.application.routes.draw do
  resources :cocktails, only: [:show, :index, :new, :create] do
  resources :doses, only: [:create, :destroy]
  end
  resources :ingredients, only: [:show]

  root "cocktails#index"
end

rails-mister-cocktail/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rails-mister-cocktail/app/models/cocktail.rb
class Cocktail < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
end

rails-mister-cocktail/app/models/dose.rb
class Dose < ApplicationRecord
  validates :description, :cocktail, :ingredient, presence: true
  validates :ingredient, uniqueness: { scope: :cocktail }
  belongs_to :cocktail
  belongs_to :ingredient
end

rails-mister-cocktail/app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  has_many :doses, dependent: :destroy
  has_many :cocktails, through: :doses
end

rails-mister-cocktail/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

rails-mister-cocktail/app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  # GET /cocktails
  def index
    @cocktails = Cocktail.all
  end

  # GET /cocktails/1
  def show
    @cocktail = Cocktail.find(params[:id])
    @dose = Dose.new
  end

  # GET /cocktails/new
  def new
    @cocktail = Cocktail.new
  end

  # POST /cocktails
  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  private
  # Never trust parameters from the scary internet, only allow the white list through.
  def cocktail_params
    params.require(:cocktail).permit(:name)
  end
end

rails-mister-cocktail/app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_cocktail
  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render "cocktails/show"
    end
  end
  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@cocktail)
  end

  private
  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end
  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

rails-mister-cocktail/app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def show
    @ingredient = Ingredient.find(params[:id])
  end
end

rails-mister-cocktail/app/helpers/application_helper.rb
module ApplicationHelper
end

rails-mister-cocktail/app/helpers/cocktails_helper.rb
module CocktailsHelper
end

rails-mister-cocktail/app/helpers/doses_helper.rb
module DosesHelper
end

rails-mister-cocktail/app/helpers/ingredients_helper.rb
module IngredientsHelper
end

rails-mister-cocktail/app/views/cocktails/_form.html.erb
<%= simple_form_for(@cocktail) do |f| %>
    <%= f.input :name, placeholder: "DANTE YOU ARE AWESOME :)" %>
    <%= f.button :submit, class: "btn btn-primary"  %>
<% end %>

rails-mister-cocktail/app/views/cocktails/index.html.erb
<br>
<h1 class="text-center"><strong>DANTE'S <u>SWEET</u> COCKTAIL LIST</strong></h1>

<div class="text-center padded">
  <%= link_to "Create a sweet, sweet cocktail, yo!", new_cocktail_path, class: "btn btn-primary" %>
</div>

<div class="container">
  <div class="row">
    <% @cocktails.each do |cocktail| %>
      <div class="col-xs-12 col-sm-4">
        <div class="card text-center">

          <% if cocktail.picture %>
            <div class="card-header" style="background-image: url('<%= image_path cocktail.picture%>')">
            </div>
          <% else %>
            <div class="card-header" style="background-image: url('http://www.seriouseats.com/images/2014/11/20141104-cocktail-party-old-fashioneds-holiday-vicky-wasik-3.jpg')">
            </div>
          <% end %>
          <div class="card-body">
            <%= link_to cocktail.name, cocktail_path(cocktail) %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

rails-mister-cocktail/app/views/cocktails/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h1>DANTE'S New Cocktail</h1>
      <%= render 'form' %>
      <%= link_to 'Back', cocktails_path %>
    </div>
  </div>
</div>

rails-mister-cocktail/app/views/cocktails/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h1><%= @cocktail.name %></h1>
      <%= link_to 'Back', cocktails_path %>

      <ul>
        <% @cocktail.doses.each do |dose| %>
          <li>
            <%= dose.description %> of <%= link_to dose.ingredient.name, ingredient_path(dose.ingredient) %>
            (<%= link_to "delete", cocktail_dose_path(@cocktail, dose), method: :delete %>)
          </li>
        <% end %>
      </ul>



      <%= simple_form_for [@cocktail, @dose] do |f| %>

        <% if @dose.errors.any? %>
          <ul>
          <% @dose.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        <% end %>

        <%= f.input :description, placeholder: "put lots of vodka in dat shizzle" %>
        <%= f.input :ingredient_id, collection: Ingredient.all, prompt: "Choose one" %>

        <%= f.submit "Add dose", class: "btn btn-primary"%>
      <% end %>
    </div>
  </div>
</div>

rails-mister-cocktail/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsBoilerplateWithConfig</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>